### ISSUE TITLE
`net` module wrapper doesn't override host argument?

### ISSUE THREAD

**Issue by Marak** [nodejitsu/haibu-carapace#15]
I saw an issue where an application was explicitly listening to `localhost`, this was preventing it from being seen on the network. 

Can we also add the ability to override the host argument passed to `net.listen`?

**Comment by stolsma** [comment]
Thats why I added the `addr` property in the event thats being send by carapace (in issue #9). It would indeed be nice if it was possible to override the addr in net.listen too with another `addr`.

**Comment by indexzero** [comment]
This is fixed.
