### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by stolsma** [nodejitsu/haibu-carapace#3]
First of all: I like the progress made with Haibu!! Just came back from a 4 week holiday and was surprised to see the nice structural changes!! Keep on going!! :-)

But when installing all the needed packages for the new version of Haibu I had some problems getting haibu-carapace installed. Every time I did a npm install I got:

```
> haibu-carapace@0.2.2 preinstall /home/sander/Development/haibu/node_modules/haibu-carapace
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /home/sander/local/node 
'configure' finished successfully (0.154s)
Waf: Entering directory `/home/sander/Development/haibu/node_modules/haibu-carapace/build'
[1/2] cxx: src/evref.cc -> build/default/src/evref_1.o
../src/evref.cc:1:21: error: node/ev.h: No such file or directory
../src/evref.cc:2:21: error: node/v8.h: No such file or directory
../src/evref.cc:4: error: ‘v8’ is not a namespace-name
../src/evref.cc:4: error: expected namespace-name before ‘;’ token
../src/evref.cc:6: error: expected constructor, destructor, or type conversion before ‘<’ token
../src/evref.cc:11: error: expected constructor, destructor, or type conversion before ‘<’ token
../src/evref.cc:17: error: variable or field ‘init’ declared void
../src/evref.cc:17: error: ‘Handle’ was not declared in this scope
../src/evref.cc:17: error: ‘Object’ was not declared in this scope
../src/evref.cc:17: error: ‘target’ was not declared in this scope
Waf: Leaving directory `/home/sander/Development/haibu/node_modules/haibu-carapace/build'
Build failed:  -> task failed (err #1): 
    {task: cxx evref.cc -> evref_1.o}
```

Got the same error when installing haibu-carapace standalone... :-(

When I changed the location of the includes in `src/evref.cc` from:

```
#include <node/ev.h>
#include <node/v8.h>
```

To:

```
#include <ev.h>
#include <v8.h>
```

I got everything working...

Any idea what is wrong with my node or npm setup ??

Thanks!!

PS: node v0.4.10 and npm 1.0.22

**Comment by Marak** [comment]
Well thats no good. I can't comment on the specific error, but I'm assuming something went wrong with the daemon.node install ( since that is the only c++ addon required ).

Hopefully we can get a better answer when some of the other developers wake up :-)

**Comment by indexzero** [comment]
`haibu-carapace` has it's own add-on, which is specific bindings to libev for referencing and dereferencing the event loop. @indutny said he had this problem as well last night. Are you compiling on x64 builds of Linux?

**Comment by stolsma** [comment]
Yep, I'm on FC13 2.6.33.3-85.fc13.i686 as a development virtual machine and had the same problem on a Ubuntu x64 test virtual machine.

But as said, changing the location of the includes now lets me compile haibu-carapace and just minutes ago I was capable to start haibu (after waiting the whole day for the problems with the NPM registry to go away :-( ) I didn't have time yet to do the vows tests included with haibu to check if changing the includes really solves the problem. Will do that tomorrow, its now friday evening 23:05 up here so time to call it a day.... :-)

**Comment by stolsma** [comment]
After some bug hunting (see one pull req for haibu-carapace and one for haibu itself) I was capable to start Haibu en get through the most important tests. So changing the two include lines solved the compiling problems..

**Comment by indutny** [comment]
That's what I get when trying to install it now: https://gist.github.com/94d8a585a252caafa56c /cc @bmeck

**Comment by indutny** [comment]
Sorry, I was using nodejs 0.5.x , wfm on 0.4.x
